### PR TITLE
Corrected MUTX component behavior when changing number of coils.

### PR DESCRIPTION
**Pull request by in3otd**
Here are my corrections to the MUTX component. I did some tests and now it seems to work fine when adding and/or removing inductors.
Note that I have modified the code so that when changing the number of inductors the existing values for the L and k are preserved.
Please check if this code works fine also on your side.

### CODE REVIEW

**Comment by ra3xdh** [comment]
@in3otd , all works fine, but there is a bug. Step to reproduce it.
1. Place on circuit MutualX with default 4 coils.
2. Go to properties.
3. Increase coils number to 8. Press Apply. 
4. Qucs hang about 1-3 seconds. Properties dialog is blocked during this time. After that time properties are updated. If OK was pressed instead of Apply, dialog closes only after 1-3 seconds.

The same behavior is for all coil numbers greater than 4. If you try to reduce coil number, all works fine without bugs.

**Comment by in3otd** [comment]
ah, my bad... I saw there was some delay when adding several coils, but I thought it was due to the debugging mode turned on... let me do some further check...

**Comment by ra3xdh** [comment]
It seems to be fixed. See last commit in my branch `mutualx_fix`

**Comment by in3otd** [comment]
uhm, well, the reason for all those loops and checks when adding (deleting) coils was because I wanted to maintain the existing `k` values when adding (deleting) coils; for example, if at the beginning I have 4 coils, with `k12`, `k13`, `k14`,  `k23`, `k24` and `k34` when I add a fifth coil I would like that **only** the new coefficients `k15`, `k25`, `k35` and `k45` receive a default value of 0.9, the old ones should maintain the previous values. I think that simply adding the properties at the end will mix up all the existing coupling values.

**Comment by ra3xdh** [comment]
@in3otd , See the last commit. There is a next attempt to fix... Results:
1. Save/load and copy/paste works correct
2. Add/Remove inductors works
3. New coupling coefficient pairs don't overwrite old.

You can see result for 6 --> 8 inductors change on screenshot. New coupling coefficients have "false" visibility attributes. 
mutx_fix

**Comment by in3otd** [comment]
ooops, seems we worked on the code at the same time, I just opened a pull request with the corrections I did in the meantime... let me check your changes...

**Comment by in3otd** [comment]
ok, did a quick check and your solution works well also here and is more compact than mine, so I will close my pull request with my fix.
I guess a similar compact code could be used when removing coils, but I will leave to you to modify that part, if you wish :grin:

**Comment by ra3xdh** [comment]
There is another bug. Step to represent:
1. Create coil with less than 4 inductors.
2. Copy/Paste it.
3. The last coupling coefficient gets default value k=0.9 

This bug was presented before my changes

**Comment by ra3xdh** [comment]
The reason of such behavior lays in `load()` method of `Component` class. MutualX inherits `MultiViewComponent` class. All MultiViewComponents uses minimal default section number. If we set default coils number to minimal amount for MutX too, this bug disappears. Copy/Paste of MutX with coil number less than four become working. It is only way to fix this bug. Maybe you can suggest a best solution. See my last commit. Please check it carefully.

**Comment by in3otd** [comment]
I think your analysis of the origin of the problem is correct. When pasting a component the `load()` method will always force to component to have a number of properties equal to the default specified there, so there is no way if the component should have less properties.
I have tried your latest code with different number of inductors and copying/pasting/saving/reloading and everything seems fine here also.
Pleas update the comment in `component.cpp`, it should now be `// number of properties for the default MUTX (`**`2`**`inductors)`

Another small thing **not** related to the `MUTX` component, is that when you enter a valid number of coils and click `Apply` the related field is correctly updated, while if you have already only 2 inductors and enter a number of coils < 2 and click `Apply` the Component Dialog shows the invalid number of coils, as if it were a valid number (the component is correctly updated). Same is for 8 inductors and a number > 8 entered. The problem is due to the check [here](https://github.com/Qucs/qucs/blob/master/qucs/qucs/components/componentdialog.cpp#L1027): since the number of properties do not change, the Component Dialog is not updated. This is not a big deal, but the problem with the `load()` method and this issue show that maybe the way `Qucs` currently handles the MultiViewComponents could be improved (with an additional flag telling the component status, `INIT`, `CHANGED`, etc., maybe).

**Comment by ra3xdh** [comment]
Comment in `component.cpp` and properties update behavior fixed. See last commit. I suggest to merge this after you perform checking.

**Comment by in3otd** [comment]
...sorry for being picky, but now the behavior of the Component Properties dialog is less user-friendly: now `updateCompPropsList()` is called every time a property is modified and the side effect is that the current (selected) property is reset to the first one after every modification.
Try to change all the coupling values of a 6 or 8-inductor `MUTX` and you will see that is not very nice to have to scroll down to look for the next property to modify at every time you click `Apply.`
IMHO, for the time being, you can leave the things as they were before: only a particular case for `MUTX` is affected, and we can think later on how to better address it. With this change the Component Dialog for every component is affected and less easier to use.

Apart from this, I have played a bit with `MUTX` and seems working fine now, thanks.

**Comment by ra3xdh** [comment]
@in3otd , I have reverted `componentdialog.cpp` . Can we now merge?

**Comment by in3otd** [comment]
yes, thanks!

**Pull request merged**
